#!/bin/bash

NPM_INSTALL_DEPENDENCIES=

while [[ $# -gt 0 ]]; do
    case $1 in
    -i | --install-dependencies)
        NPM_INSTALL_DEPENDENCIES=true
        shift
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

cd "$(dirname "$0")/../Node"

if [ "$NPM_INSTALL_DEPENDENCIES" = true ]; then
    npm install
fi

npm run dump-idl --silent > idl.json
